### ISSUE TITLE
learn tests not working

### ISSUE THREAD

**Issue by danvyle** [learn-co-curriculum/fewpjs-js-fundamentals-variables#4]
hitting this error: /Users/Dan-VyLe/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by sgharms** [comment]
Hi @danvyle 

Looking at this repo, I don't see that there are any tests here. It appears to be a README. Furthermore, that error appears to be a Ruby error (`mocha.rb`) when this is a lab for JavaScript.  When I checked your fork of this repo, it seems also to be a readme.

Did you mean to open this issue on a different repository? I'm going to assume this issue was opened on the wrong repo. Please open an issue on the repo with the bug, or reopen this issue if there are more details you can provide. Thanks!
